name: Build Site 
on:
  push:
#    paths:
#      - '_data/portals/*.json'
  pull_request:
#    paths:
#      - '_data/portals/*.json'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@v0.82.0  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --buildDrafts
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './public'
